/* automatically generated by rust-bindgen */

extern "C" {
    pub fn TextToSentences(
        pInUtf8Str: *const ::std::os::raw::c_char,
        InUtf8StrByteCount: ::std::os::raw::c_int,
        pOutUtf8Str: *mut ::std::os::raw::c_char,
        MaxOutUtf8StrByteCount: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn TextToWords(
        pInUtf8Str: *const ::std::os::raw::c_char,
        InUtf8StrByteCount: ::std::os::raw::c_int,
        pOutUtf8Str: *mut ::std::os::raw::c_char,
        MaxOutUtf8StrByteCount: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
