#!/bin/bash
set +x
set -e
set -o pipefail

cd "$(dirname "$0")"

echo "#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]" > src/lib.rs

bindgen --whitelist-function TextToWords --whitelist-function TextToSentences --whitelist-type FALimits BlingFire/blingfiretools/blingfiretokdll/blingfiretokdll.cpp -- -IBlingFire/blingfireclient.library/inc -IBlingFire/blingfirecompile.library/inc -DBLING_FIRE_NOWINDOWS -DBLING_FIRE_NOAP -x c++ >> src/lib.rs
